// Generated by CoffeeScript 1.6.3
var customAsynchronousValidator, customValidator;

customValidator = function(field, value, cb) {
  if (value !== 'custom') {
    cb(field, 'Example error from custom validator.');
    return false;
  }
  cb(field);
  return true;
};

customAsynchronousValidator = function(field, value, cb) {
  $.get('./customAsynchronousValidator.php', {
    field: field,
    value: value
  }, function(d) {
    if (d.err) {
      return cb(field, d.err);
    } else {
      return cb(field);
    }
  }, 'json').error(function() {
    return cb(field, 'AJAX Error - custom validator requires ./customAsynchronousValidator.php to be working.');
  });
  return false;
};

$(function() {
  var valid;
  valid = new Valid8r({
    bindToBlur: true,
    form: '#example-form',
    callback: function(field, err) {
      var e, o;
      o = $('#' + field).parents('.form-group');
      if (err) {
        o.addClass('has-error').removeClass('has-success');
        e = o.find('.help-block');
        if (!e.length) {
          if ((o.find('.rule').length)) {
            e = $('<div class="help-block"></div>').insertBefore(o.find('.rule'));
          } else {
            e = $('<div class="help-block"></div>').appendTo(o);
          }
        }
        return e.html(err).show();
      } else {
        o.removeClass('has-error').addClass('has-success');
        return o.find('.help-block').hide();
      }
    }
  });
  return $.get('./kitchen-sink.json', function(d) {
    return valid.setRules(d);
  }, 'json');
});
