// Generated by CoffeeScript 1.6.3
var customValidator;

customValidator = function(field, value) {
  console.log('Custom Validator called with: ', field, value);
  if (value !== 'custom') {
    return 'Example error from custom validator.';
  }
  return '';
};

$(function() {
  var valid;
  valid = new Valid8r({
    bindToBlur: true,
    form: '#example-form',
    callback: function(field, err) {
      var e, o;
      o = $('#' + field).parents('.form-group');
      if (err) {
        o.addClass('has-error').removeClass('has-success');
        e = o.find('.help-block');
        if (!e.length) {
          if ((o.find('.rule').length)) {
            e = $('<div class="help-block"></div>').insertBefore(o.find('.rule'));
          } else {
            e = $('<div class="help-block"></div>').appendTo(o);
          }
        }
        return e.html(err).show();
      } else {
        o.removeClass('has-error').addClass('has-success');
        return o.find('.help-block').hide();
      }
    }
  });
  return $.get('./kitchen-sink.json', function(d) {
    return valid.setRules(d);
  }, 'json');
});
